### ISSUE TITLE
Newer version is available (9.011.01 - 2023/04/25)

### ISSUE THREAD

**Issue by arbv** [LouisTakePILLz/r8125#2]
Please consider updating the repository.

https://www.realtek.com/en/component/zoo/category/network-interface-controllers-10-100-1000m-gigabit-ethernet-pci-express-software

**Comment by notpeelz** [comment]
I missed a couple versions because I didn't have a need for this driver anymore, but here you go: 6f90eb46538b2d8974848ca0b6e475c79a1ab53e

**Comment by arbv** [comment]
Thank you!

**Comment by notpeelz** [comment]
You're welcome! :)
